# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streamer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'streamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estreamer.proto\"/\n\x10\x41pplicationUsage\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\x0e\n\x06lapsed\x18\x02 \x01(\x05\"\xb6\x01\n\x10StreamLogRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x0b\n\x03\x61pp\x18\x03 \x01(\t\x12\x0e\n\x06lapsed\x18\x04 \x01(\x05\x12\x19\n\x11\x61gent_last_online\x18\x05 \x01(\t\x12\x18\n\x10user_last_online\x18\x06 \x01(\t\x12\x10\n\x08username\x18\x07 \x01(\t\x12\r\n\x05orgid\x18\x08 \x01(\t\x12\r\n\x05\x61lias\x18\t \x01(\t\"4\n\x11StreamLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"|\n\x0eInitLogRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x13\n\x0bos_platform\x18\x03 \x01(\t\x12\x12\n\nos_version\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\x12\r\n\x05orgid\x18\x06 \x01(\t\"2\n\x0fInitLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2~\n\x10StreamLogService\x12\x30\n\x0bInitLogData\x12\x0f.InitLogRequest\x1a\x10.InitLogResponse\x12\x38\n\rStreamLogData\x12\x11.StreamLogRequest\x1a\x12.StreamLogResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATIONUSAGE']._serialized_start=18
  _globals['_APPLICATIONUSAGE']._serialized_end=65
  _globals['_STREAMLOGREQUEST']._serialized_start=68
  _globals['_STREAMLOGREQUEST']._serialized_end=250
  _globals['_STREAMLOGRESPONSE']._serialized_start=252
  _globals['_STREAMLOGRESPONSE']._serialized_end=304
  _globals['_INITLOGREQUEST']._serialized_start=306
  _globals['_INITLOGREQUEST']._serialized_end=430
  _globals['_INITLOGRESPONSE']._serialized_start=432
  _globals['_INITLOGRESPONSE']._serialized_end=482
  _globals['_STREAMLOGSERVICE']._serialized_start=484
  _globals['_STREAMLOGSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
